import {uiText} from '../lib/i18n';
import {useEffect,useState} from 'react';
import {notifyEditorSuccess} from './editor-feedback';
import {useI18n} from '../lib/i18n';
export function KnowledgeGenerator({onCreated}:{onCreated:()=>void}){
 const {t}=useI18n();
 const [topic,setTopic]=useState(''),[direction,setDirection]=useState(''),[search,setSearch]=useState(false),[available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const load=()=>{fetch('/api/web-search').then(r=>r.json()).then(d=>{const ok=!!d.knowledgeEnabled&&!!d.hasKey;setAvailable(ok);if(!ok)setSearch(false);}).catch(()=>setAvailable(false));};load();window.addEventListener('focus',load);return()=>window.removeEventListener('focus',load);},[]);
 async function generate(){setBusy(true);setMessage(uiText("building_knowledge"));try{const r=await fetch('/api/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'generate',topic,direction,search:search&&available})});const d=await r.json();if(!r.ok)throw Error(d.error);const notice=t('knowledge.createdFiles').replace('{name}',d.generated.name).replace('{count}',String(d.generated.files.length));setMessage(notice);notifyEditorSuccess(notice);onCreated();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 return <section className="knowledge-generator"><header><span className="settings-eyebrow">{uiText("knowledge.aiStudio")}</span><h3>{uiText("from_an_idea_build_a_body_of_knowledge")}</h3><p>{uiText("describe_the_topic_and_purpose_ai_will_organize_the_complete_knowledge_content_without_attaching_external_urls")}</p></header><label>{uiText("topic")}<input value={topic} maxLength={200} onChange={e=>setTopic(e.target.value)} placeholder={uiText("for_example_japanese_high_school_club_activity_knowledge")}/></label><label>{uiText("direction")}<textarea rows={3} maxLength={2000} value={direction} onChange={e=>setDirection(e.target.value)} placeholder={uiText("applicable_role_required_knowledge_tone_or_situation")}/></label><label><input type="checkbox" checked={search} disabled={!available||busy} onChange={e=>setSearch(e.target.checked)}/>{uiText("use_web_search_for_research")}</label>{!available&&<p>{uiText("please_enable_web_search_in_the_system_settings_first_and_save_the_api_key")}</p>}<button className="primary" disabled={busy||!topic.trim()} onClick={()=>void generate()}>{busy?uiText("creating"):uiText("create_and_store_knowledge")}</button><p role="status">{message}</p></section>;
}
