import {uiText} from '../lib/i18n';
import {useEffect,useState} from 'react';
import {Folder,FileText,ChevronRight,ChevronDown,Trash2,Save,Plus,RefreshCw} from 'lucide-react';
import {KnowledgeGenerator} from './knowledge-generator';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Switch} from './ui/switch';
import {notifyEditorSuccess} from './editor-feedback';
import {useI18n} from '../lib/i18n';
type Entry={path:string;directory:boolean;bytes:number};
type Knowledge={name:string;description:string;enabled:boolean;error?:string};
export function KnowledgeEditor(){
 const {t}=useI18n();
 const [tree,setTree]=useState<Entry[]>([]),[knowledge,setKnowledge]=useState<Knowledge[]>([]),[expanded,setExpanded]=useState<Set<string>>(new Set()),[selected,setSelected]=useState(''),[text,setText]=useState(''),[saved,setSaved]=useState(''),[root,setRoot]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [confirm,setConfirm]=useState<{title:string;description:string;action:()=>void}|null>(null),[create,setCreate]=useState<'file'|'folder'|'knowledge'|''>(''),[name,setName]=useState('');
 const [aiOpen,setAiOpen]=useState(false);
 const dirty=text!==saved,entry=tree.find(e=>e.path===selected),knowledgeEntry=knowledge.find(s=>s.name===selected.split('/')[0]);
 async function request(body?:unknown){const r=await fetch('/api/knowledge',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d=await r.json();if(!r.ok)throw Error(d.error);if(d.tree)setTree(d.tree);if(d.knowledge)setKnowledge(d.knowledge);if(d.root)setRoot(d.root);if(body&&typeof body==='object'&&'type' in body&&(body as {type?:string}).type==='save')notifyEditorSuccess(uiText("the_knowledge_base_has_been_saved"));return d;}
 async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 useEffect(()=>{void run(async()=>{await request();});},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function guard(action:()=>void){if(dirty)setConfirm({title:uiText("discard_unsaved_changes"),description:t('knowledge.unsavedDescription').replace('{name}',selected),action});else action();}
 function choose(e:Entry){guard(()=>void run(async()=>{setSelected(e.path);setText('');setSaved('');const d=e.directory?{text:''}:await request({type:'read',path:e.path});setText(d.text);setSaved(d.text);}));}
 function rows(parent='',depth=0):React.ReactNode{return tree.filter(e=>e.path.split('/').slice(0,-1).join('/')===parent&& !e.path.endsWith('/.disabled')).sort((a,b)=>Number(b.directory)-Number(a.directory)||a.path.localeCompare(b.path)).map(e=><div key={e.path}><div className={'knowledge-tree-row '+(selected===e.path?'selected':'')} style={{paddingLeft:8+depth*16}}><button className="tree-expander" aria-label={expanded.has(e.path)?uiText("collapse_folder"):uiText("expand_folder")} disabled={!e.directory} onClick={()=>setExpanded(old=>{const next=new Set(old);next.has(e.path)?next.delete(e.path):next.add(e.path);return next;})}>{e.directory?(expanded.has(e.path)?<ChevronDown size={14}/>:<ChevronRight size={14}/>):null}</button><button className="tree-name" disabled={busy} onClick={()=>choose(e)}>{e.directory?<Folder size={16}/>:<FileText size={16}/>}<span>{e.path.split('/').at(-1)}</span></button></div>{e.directory&&expanded.has(e.path)&&rows(e.path,depth+1)}</div>);}
 function begin(kind:'file'|'folder'|'knowledge'){guard(()=>{setCreate(kind);setName(kind==='knowledge'?'':(entry?.directory?selected+'/':selected.includes('/')?selected.slice(0,selected.lastIndexOf('/')+1):''));});}
 async function make(){await run(async()=>{const p=name.trim();if(!p)throw Error(uiText("please_enter_a_name"));if(tree.some(e=>e.path===p))throw Error(uiText("the_name_already_exists"));if(create==='folder')await request({type:'mkdir',path:p});else{const path=create==='knowledge'?p+'/KNOWLEDGE.md':p;const body=create==='knowledge'?t('knowledge.defaultTemplate').replace('{name}',p):'';await request({type:'save',files:[{path,text:body}]});setSelected(path);setText(body);setSaved(body);}setExpanded(old=>new Set([...old,...p.split('/').map((_,i)=>p.split('/').slice(0,i+1).join('/'))]));setCreate('');setMessage(uiText("established"));});}
 function remove(){setConfirm({title:entry?.directory?uiText("delete_folder"):uiText("delete_file"),description:t('knowledge.deleteDescription').replace('{name}',selected).replace('{contents}',entry?.directory?t('knowledge.deleteContents'):'').replace('{knowledge}',selected.endsWith('/KNOWLEDGE.md')?t('knowledge.deleteKnowledge'):'').replace('{dirty}',dirty?t('knowledge.deleteDirty'):''),action:()=>void run(async()=>{await request({type:'delete',path:selected});setSelected('');setText('');setSaved('');setMessage(uiText("has_been_deleted"));})});}
 return <div className="editor-detail knowledge-workspace"><header><span className="settings-eyebrow">{uiText("knowledge.libraryEyebrow")}</span><h2>{uiText("knowledge_library_2")}</h2><p>{uiText("browse_the_entire_set_of_documents_and_manage_reference_knowledge_for_model_use")}</p></header><div className="button-row"><button disabled={busy} onClick={()=>begin('knowledge')}><Plus size={16}/>{uiText("add_knowledge")}</button><button disabled={busy} onClick={()=>guard(()=>void run(async()=>{await request();}))}><RefreshCw size={16}/>{uiText("rescan")}</button><label className="knowledge-import">{uiText("import_folder")}<input type="file" multiple {...{webkitdirectory:''}} disabled={busy} onChange={e=>{const files=Array.from(e.target.files??[]);guard(()=>void run(async()=>{if(files.length>100)throw Error(uiText("maximum_100_files_at_a_time"));const entries=[];for(const f of files){if(f.size>65536)throw Error(uiText("maximum_single_file_size_is_64kb"));entries.push({path:f.webkitRelativePath||f.name,text:new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer())});}await request({type:'save',files:entries});setSelected('');setText('');setSaved('');setMessage(uiText("has_been_imported"));}));e.target.value='';}}/></label></div>
 {message&&<p role="status" className="knowledge-feedback">{message}</p>}
<div className="knowledge-explorer"><aside aria-label={uiText("knowledge_archive_structure")}><div className="knowledge-pane-heading">{uiText("files_3")} <small>{tree.filter(e=>!e.directory).length} {uiText("files")}</small></div><div className="knowledge-tree">{tree.length?rows():<p className="empty-copy">{uiText("no_files_yet_add_or_import_the_first_knowledge")}</p>}</div><small className="knowledge-root">{root}</small></aside><section className="knowledge-file-panel"><div className="knowledge-pane-heading"><span>{selected||uiText("select_a_file")}{dirty?` ${uiText("not_saved")}`:''}</span><div className="knowledge-file-actions"><button title={uiText("add_file")} disabled={busy} onClick={()=>begin('file')}><FileText size={16}/>{uiText("add_file")}</button><button title={uiText("add_folder")} disabled={busy} onClick={()=>begin('folder')}><Folder size={16}/>{uiText("add_folder")}</button><button title={uiText("delete_selected_item")} disabled={busy||!entry} onClick={remove}><Trash2 size={16}/></button></div></div>
 {knowledgeEntry&&<div className="knowledge-metadata"><span>{knowledgeEntry.error??knowledgeEntry.description}</span><label>{uiText("enable")} <Switch checked={knowledgeEntry.enabled} disabled={busy||!!knowledgeEntry.error} onCheckedChange={enabled=>void run(async()=>{await request({type:'toggle',name:knowledgeEntry.name,enabled});})}/></label></div>}
 {entry&&!entry.directory?<><textarea aria-label={uiText("file_contents")} spellCheck={false} value={text} disabled={busy} onChange={e=>setText(e.target.value)}/><footer><small>{text.length.toLocaleString()} {uiText("characters_2")} {selected.endsWith('KNOWLEDGE.md')?uiText("knowledge_definition"):uiText("reference_documents")}</small><button className="primary" disabled={busy||!dirty} onClick={()=>void run(async()=>{await request({type:'save',files:[{path:selected,text}]});setSaved(text);setMessage(uiText("has_been_saved_and_will_take_effect_next_time_it_is_generated"));})}><Save size={16}/>{uiText("save_changes")}</button></footer></>:<div className="knowledge-file-empty"><Folder size={36}/><h3>{entry?uiText("folder_contents"):uiText("open_the_file_from_the_left")}</h3><p>{entry?uiText("expand_the_folder_on_the_left_to_browse_you_can_also_add_files_or_subfolders_here"):uiText("you_can_edit_files_after_selecting_them_folders_and_files_can_be_deleted")}</p></div>}</section></div>
 <div className="button-row"><button className="primary" disabled={busy} onClick={()=>setAiOpen(true)}>{uiText("create_knowledge_with_ai")}</button></div>
 <Dialog open={aiOpen} onOpenChange={setAiOpen}><DialogContent className="knowledge-generator-dialog"><DialogTitle>{uiText("create_knowledge_with_ai")}</DialogTitle><DialogDescription>{uiText("enter_the_topic_and_direction_to_create_a_complete_knowledge_file_optionally_use_web_search_to")}</DialogDescription><KnowledgeGenerator onCreated={()=>void run(async()=>{await request();})}/></DialogContent></Dialog>
 <Dialog open={!!confirm} onOpenChange={open=>{if(!open&&!busy)setConfirm(null);}}><DialogContent><DialogTitle>{confirm?.title}</DialogTitle><DialogDescription>{confirm?.description}</DialogDescription><div className="button-row"><button onClick={()=>setConfirm(null)}>{uiText("cancel")}</button><button className="primary" onClick={()=>{const action=confirm?.action;setConfirm(null);action?.();}}>{uiText("confirm")}</button></div></DialogContent></Dialog>
 <Dialog open={!!create} onOpenChange={open=>{if(!open&&!busy)setCreate('');}}><DialogContent><DialogTitle>{uiText("add")}{create==='knowledge'?uiText("knowledge"):create==='folder'?uiText("folder"):uiText("archives")}</DialogTitle><DialogDescription>{create==='knowledge'?uiText("enter_the_english_name_in_lowercase_hyphens_can_be_used"):uiText("enter_a_relative_path_such_as_my_knowledge_references_notes_md")}</DialogDescription><input aria-label={uiText("add_project_path")} value={name} onChange={e=>setName(e.target.value)}/>{message&&<p role="alert">{message}</p>}<button className="primary" disabled={busy||!name.trim()} onClick={()=>void make()}>{uiText("create")}</button></DialogContent></Dialog>
 </div>;
}
