import {uiText} from '../lib/i18n';
import {sdProfiles} from '../../core/sd-profiles';
import {useState} from 'react';
import {Info,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
export function StableDiffusionHelp(){
 const [open,setOpen]=useState(false);
 return <><button type="button" className="sd-info-button" aria-label={uiText("stable_diffusion_installation_and_interface_setting_instructions")} title={uiText("installation_and_interface_setting_instructions")} onClick={()=>setOpen(true)}><Info size={20}/></button>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sd-help-dialog"><DialogTitle>{uiText("local_drawing_installation_and_settings")}</DialogTitle><DialogDescription>{uiText("install_webui_illustrious_or_pony_model_and_corresponding_character_lora_and_then_enable_the_api_to")}</DialogDescription>
 <section><h3>{uiText("message_1_install_stable_diffusion_webui")}</h3><p>{uiText("windows_please_install_python_3_10_6_first_check_add_python_to_path_during_installation_and")}</p><pre><code>{'git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git\ncd stable-diffusion-webui'}</code></pre><p>{uiText("according_to")} <a href="https://github.com/AUTOMATIC1111/stable-diffusion-webui#installation-and-running" target="_blank" rel="noreferrer">{uiText("official_installation_guide")}</a>{uiText("complete_environment_please_refer_to_the_same_guide_for_other_operating_systems")}</p></section>
 <section><h3>{uiText("message_2_select_the_base_model_and_role_lora")}</h3>{(['Illustrious','Pony'] as const).map(family=><div key={family}><h4>{uiText(family==='Illustrious'?"technical.illustrious":"technical.pony")}</h4><p>{uiText("recommended")} <a href={sdProfiles[family].modelUrl} target="_blank" rel="noreferrer">{sdProfiles[family].label}</a></p><a className="sd-lora-download" href={sdProfiles[family].loraUrl} target="_blank" rel="noreferrer"><Download size={18}/>{uiText("download")} {uiText(family==='Illustrious'?"technical.illustrious":"technical.pony")} {uiText("technical.lora_zip")}</a><p>{uiText("unzip_to")} <code>{uiText("technical.stable_diffusion_webui_models_lora")}{family}/</code>{uiText("retain_the_character_subfolder_and_original_file_name")}</p></div>)}</section>
 <section><h3>{uiText("message_3_install_the_model")}</h3><p>{uiText("the_main_model_is_downloaded_separately_and_placed_in")} <code>{uiText("technical.models_stable_diffusion_illustrious")}</code> {uiText("or")} <code>{uiText("technical.models_stable_diffusion_pony")}</code>{uiText("if_the_lora_zip_already_contains_lora_or_model_type_folders_please_merge_the_directories_with")}</p><p>{uiText("the_game_settings_must_select_the_same_model_type_and_fill_in_the_full_checkpoint_name")} <code>{uiText("technical.models_lora_illustrious")}</code> {uiText("or")} <code>{uiText("technical.models_lora_pony")}</code> {uiText("in_lora_the_actual_name_is_read_through_the_webui_api")}</p></section>
 <section><h3>{uiText("message_4_start_the_api_service")}</h3><p>{uiText("open_with_text_editor")} <code>{uiText("technical.webui_user_bat")}</code>{uiText("set_the_startup_parameters_to")}</p><pre><code>{uiText("technical.set_commandline_args_api")}</code></pre><p>{uiText("if_there_are_other_parameters_add_them_after_the_original_parameters")} <code>{uiText("technical.api")}</code> {uiText("will_do_execute_after_saving")} <code>{uiText("technical.webui_user_bat")}</code>{uiText("waiting_for_environment_installation_and_model_loading_windows_users_who_have_already_created_a_venv_can")}</p><pre><code>{'.\\venv\\Scripts\\python.exe launch.py --api'}</code></pre><p>{uiText("open_in_browser")} <code>{uiText("technical.http_127_0_0_1_7860_docs")}</code>{uiText("confirm_that_there_is")} <code>{uiText("technical.sdapi_v1_txt2img")}</code>{uiText("just_because_the_web_page_is_open_does_not_mean_that_the_api_is_open_local")}</p></section>
 <section><h3>{uiText("message_5_connect_to_games")}</h3><p>{uiText("return_to_this_card_enable_image_generation_and_fill_in_the_service_url")} <code>{uiText("technical.http_127_0_0_1_7860")}</code>{uiText("if_other_port_numbers_are_displayed_during_startup_fill_in_the_actual_url_generally_for_native")}</p><p>{uiText("complete_the_game_s_llm_api_settings_and_let_llm_determine_prompts_and_lora_it_is")}</p><p>{uiText("if_404_appears_check_the_url_and")} <code>{uiText("technical.api")}</code>{uiText("if_sd_returns_nan_you_can_enable_upcast_cross_attention_layer_to_float32_first_and_then")} <code>{uiText("technical.no_half")}</code> {uiText("restart")}</p></section>
 </DialogContent></Dialog></>;
}
