import {uiText} from '../lib/i18n';
import {useEffect,useState,useRef,useMemo,type ReactNode,type KeyboardEvent} from 'react';
import {ArrowLeft,Heart,MessageCircle,Repeat2,Quote,Lock,Users,Bell,Home,RefreshCw,Search,Send,Trash2,UserMinus,LoaderCircle,RotateCcw,Ban,X,CheckCheck} from 'lucide-react';
import type {Content,GameState} from '@core/types';
import {canReadTwitter,socialSettings,twitterHashtags,twitterNotificationTokens,twitterPosts,twitterPostPending,twitterTrends,type TwitterState,type TwitterPost} from '@core/twitter';
import {dayPhaseNames} from '@core/engine';
import {publicAccounts,hydratePublicAccounts} from '@core/twitter-public';
import {CharacterAvatar} from './character-avatar';
import {TwitterAccount} from './twitter-account';
import {TwitterUpload} from './twitter-upload';
import {TwitterTyping} from './twitter-typing';
import {useI18n} from '../lib/i18n';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import './twitter.css';

export function TwitterBird({size=28}:{size?:number}){return <img className="twitter-brand" src="/assets/twitter-brand.svg" width={size} height={size} alt={uiText("twitter_bluebird")}/>}

function SeenTwitterPost({id,watchKey,onSeen,children}:{id:string;watchKey:string;onSeen:()=>void;children:ReactNode}){
 const ref=useRef<HTMLElement>(null),seen=useRef(onSeen);seen.current=onSeen;
 useEffect(()=>{const element=ref.current;if(!element||!watchKey)return;let timer:ReturnType<typeof setTimeout>|undefined;const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting&&entry.intersectionRatio>=.6)){timer=setTimeout(()=>{seen.current();observer.disconnect();},500);}else if(timer){clearTimeout(timer);timer=undefined;}},{threshold:[.6]});observer.observe(element);return()=>{observer.disconnect();if(timer)clearTimeout(timer);};},[id,watchKey]);
 return <article className="tw-post" data-twitter-post={id} ref={ref}>{children}</article>;
}

export function TwitterPanel({state,content,images,onClose}:{state:GameState;content:Content;images:boolean;onClose?:()=>void}){
 const {t:translate,language}=useI18n();
 const [t,setT]=useState<TwitterState>(),[tab,setTab]=useState('home'),[profile,setProfile]=useState(''),[text,setText]=useState(''),[searchQuery,setSearchQuery]=useState(''),[photo,setPhoto]=useState(false),[busy,setBusy]=useState(false),[busyAction,setBusyAction]=useState(''),[busyTarget,setBusyTarget]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[thread,setThread]=useState(''),[focusedPost,setFocusedPost]=useState(''),[replyTarget,setReplyTarget]=useState(''),[reply,setReply]=useState(''),[replySort,setReplySort]=useState<'relevant'|'earliest'|'liked'>('relevant'),[people,setPeople]=useState<{title:string;ids:string[]}|null>(null),[deletePost,setDeletePost]=useState(''),[unfollowTarget,setUnfollowTarget]=useState(''),[blockTarget,setBlockTarget]=useState(''),[repostTarget,setRepostTarget]=useState(''),[quoteTarget,setQuoteTarget]=useState(''),[quoteText,setQuoteText]=useState(''),[mentionIndex,setMentionIndex]=useState(0),[fullReplies,setFullReplies]=useState<ReadonlySet<string>>(new Set());
 const retry=useRef<{key:string;id:string}|undefined>(undefined),mainRef=useRef<HTMLElement>(null);
 const viewRevision=useRef(-1);
 const [mentionDismissed,setMentionDismissed]=useState(false);
 const [notificationRead,setNotificationRead]=useState('');
 const notificationStorageKey='makeine-twitter-read:'+state.runId;
 useEffect(()=>{try{setNotificationRead(localStorage.getItem(notificationStorageKey)??'');}catch{setNotificationRead('');}},[notificationStorageKey]);
 useEffect(()=>{if(!error&&!notice)return;const timer=setTimeout(()=>{setError('');setNotice('')},4000);return()=>clearTimeout(timer)},[error,notice]);
 function acceptView(data:{twitter:TwitterState;revision?:number;runId?:string}){if(data.runId&&data.runId!==state.runId)return;if(typeof data.revision==='number'){if(data.revision<viewRevision.current)return;viewRevision.current=data.revision;}setT(data.twitter);}
 const officialAccounts=useMemo(()=>publicAccounts(hydratePublicAccounts(structuredClone(content),language)),[content,language]),official=(id:string)=>officialAccounts.find(account=>account.id===id);
 const me='kazuhiko',character=(id:string)=>content.characters.find(ch=>ch.id===id),name=(id:string)=>character(id)?.name??official(id)?.name??id,bio=(id:string)=>{const ch=character(id);return ch?socialSettings(ch,language).twitterBio:official(id)?.bio??'';},cover=(id:string)=>{const ch=character(id);return ch?socialSettings(ch).twitterCover:official(id)?.cover??'';};
 useEffect(()=>{let live=true,loading=false;async function load(){if(loading)return;loading=true;try{const r=await fetch('/api/twitter',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(live)acceptView(d);}catch(e){if(live)setError(String(e));}finally{loading=false;}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},400);return()=>{live=false;clearInterval(timer);};},[state.runId,state.date,state.phase]);
 useEffect(()=>{if(focusedPost)requestAnimationFrame(()=>mainRef.current?.scrollTo({top:0,behavior:'smooth'}));},[focusedPost]);
 async function act(action:string,target='',value='',image=false){
  const key=JSON.stringify({action,target,value,image,runId:state.runId});
  if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};
  setBusy(true);setBusyAction(action);setBusyTarget(target);setError('');setNotice('');
  try{const r=await fetch('/api/twitter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,target,text:value,image,runId:state.runId,requestId:retry.current.id})});const d=await r.json();if(!r.ok)throw Error(d.error);acceptView(d);setNotice(d.notice??'');retry.current=undefined;if(action==='post'){setText('');setPhoto(false);}if(action==='reply'){setReply('');setReplyTarget(thread);}if(action==='repost')setRepostTarget('');if(action==='quote'){setQuoteTarget('');setQuoteText('');setRepostTarget('');}if(action==='delete'){setDeletePost('');if(focusedPost===target)setFocusedPost('');if(thread===target)setThread('');}}
  catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);setBusyAction('');setBusyTarget('');}
 }
 async function setPlayerPrivate(value:boolean){setBusy(true);setError('');try{const r=await fetch('/api/twitter',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerPrivate:value,runId:state.runId})}),d=await r.json();if(!r.ok)throw Error(d.error);acceptView(d);setNotice(d.notice??'');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 function scrollToLatest(){requestAnimationFrame(()=>mainRef.current?.scrollTo({top:0,behavior:'auto'}));}
 function switchTab(next:string){setTab(next);setFocusedPost('');setPeople(null);setThread('');setReplyTarget('');scrollToLatest();}
 function visit(id:string){setProfile(id);switchTab('profile');}
 if(!t)return <div className="social-launch tw-launch" role="status">{onClose&&<button type="button" className="tw-app-close" aria-label={translate('twitter.closeApp')} onClick={onClose}><X size={21}/></button>}<span className="social-launch-logo"><TwitterBird size={52}/></span><LoaderCircle className="spin" size={30}/><strong>{error||uiText("opening_twitter")}</strong></div>;
 const posts=twitterPosts(t),trends=twitterTrends(t),known=content.characters.filter(ch=>state.met.includes(ch.id)||ch.id==='kaju'||ch.id===me);
 const onlineFirst=(a:Content['characters'][number],b:Content['characters'][number])=>Number(!!t.online?.includes(b.id))-Number(!!t.online?.includes(a.id));
 const asideFollowing=[...known.map(ch=>ch.id),...officialAccounts.map(account=>account.id)].filter(id=>id!==me&&t.following[me]?.[id]&&!t.blocks?.[me]?.[id]&&!t.blocks?.[id]?.[me]).sort((a,b)=>Number(!!t.online?.includes(b)||!!official(b))-Number(!!t.online?.includes(a)||!!official(a)));
 const asideSuggestions=known.filter(ch=>ch.id!==me&&!t.following[me]?.[ch.id]&&!t.blocks?.[me]?.[ch.id]&&!t.blocks?.[ch.id]?.[me]).sort(onlineFirst).slice(0,3);
 function account(id:string,showOnline=false){const item=official(id);return <TwitterAccount character={character(id)} id={id} name={item?.name} color={item?.color} avatar={item?.avatar} handle={t?.accounts[id]?.handle??id} isPrivate={!!t?.accounts[id]?.private} verified={!!t?.accounts[id]?.verified} online={showOnline&&(!!item||!!t?.online?.includes(id))} onlineLabel={translate('twitter.online')} onVisit={visit}/>;}
 function follow(id:string){if(id===me)return null;const blocked=t!.blocks?.[me]?.[id],blocksMe=t!.blocks?.[id]?.[me],follows=t!.following[me]?.[id],requested=t!.requests[id]?.[me];return <button className={'tw-follow '+(follows?'is-following':'')+(blocked?' is-blocked':'')} disabled={busy||state.ended||!!blocksMe} onClick={()=>{if(blocked)void act('unblock',id);else if(follows)setUnfollowTarget(id);else void act(requested?'unfollow':'follow',id);}}>{blocked?translate('twitter.unblock'):blocksMe?translate('twitter.blockedFollowStatus'):follows?uiText("following"):requested?uiText("cancel_request"):t!.accounts[id]?.private?uiText("request_follow"):uiText("follow")}</button>;}
 function beginReply(id:string){setReplyTarget(id);setReply('');setMentionDismissed(false);}
 function typing(id:string){const actors=[...new Set((t?.typing??[]).filter(item=>item.postId===id).map(item=>item.actor))];return actors.length?<TwitterTyping label={translate('twitter.typing').replace('{names}',actors.map(name).join('、'))}/>:null;}
 const mentionFriends=[...known.filter(ch=>ch.id!==me).map(ch=>({id:ch.id,name:ch.name,character:ch,color:ch.color})),...officialAccounts.map(item=>({id:item.id,name:item.name,character:undefined,color:item.color}))].filter(item=>!t!.blocks?.[me]?.[item.id]&&!t!.blocks?.[item.id]?.[me]);
 function mentionMatches(value:string){if(mentionDismissed)return null;const match=value.match(/(^|[^A-Za-z0-9_])@([\w]*)$/);if(!match)return null;const query=match[2].toLowerCase(),matches=mentionFriends.filter(ch=>(t!.accounts[ch.id]?.handle??ch.id).toLowerCase().includes(query)||ch.name.includes(query)).slice(0,8);return matches.length?{match,matches}:null;}
 function chooseMention(value:string,setter:(next:string)=>void,index=mentionIndex){const found=mentionMatches(value);if(!found)return false;const ch=found.matches[Math.max(0,Math.min(index,found.matches.length-1))],handle=t!.accounts[ch.id]?.handle??ch.id;setter(value.slice(0,value.length-found.match[0].length)+found.match[1]+'@'+handle+' ');setMentionIndex(0);return true;}
 function revealMentionSelection(input:HTMLTextAreaElement){requestAnimationFrame(()=>{const menu=input.parentElement?.querySelector<HTMLElement>('.tw-mention-menu'),selected=menu?.querySelector<HTMLElement>('[aria-selected="true"]');if(!menu||!selected)return;const top=selected.offsetTop,bottom=top+selected.offsetHeight;if(top<menu.scrollTop)menu.scrollTop=top;else if(bottom>menu.scrollTop+menu.clientHeight)menu.scrollTop=bottom-menu.clientHeight;});}
 function composeKeys(e:KeyboardEvent<HTMLTextAreaElement>,value:string,setter:(next:string)=>void,submit:()=>void){if(e.nativeEvent.isComposing)return;const found=mentionMatches(value);if(found&&(e.key==='ArrowDown'||e.key==='ArrowUp')){e.preventDefault();const input=e.currentTarget;setMentionIndex(i=>(i+(e.key==='ArrowDown'?1:-1)+found.matches.length)%found.matches.length);revealMentionSelection(input);return;}if(found&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();chooseMention(value,setter);return;}if(found&&e.key==='Escape'){e.preventDefault();e.stopPropagation();setMentionIndex(0);setMentionDismissed(true);return;}if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy&&!state.ended&&value.trim())submit();}}
 function mentionPicker(value:string,setter:(next:string)=>void){const found=mentionMatches(value);if(!found)return null;return <div className="tw-mention-menu" role="listbox">{found.matches.map((item,index)=>{const handle=t!.accounts[item.id]?.handle??item.id,avatar=official(item.id)?.avatar;return <button style={index===mentionIndex?{background:'var(--tw-hover)',outline:'2px solid #1da1f2',outlineOffset:'-2px'}:undefined} type="button" role="option" aria-selected={index===mentionIndex} key={item.id} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseMention(value,setter,index)}>{item.character?<CharacterAvatar character={item.character}/>:<span className="avatar tw-official-avatar" style={{background:item.color}}>{avatar&&<img src={avatar} alt=""/>}</span>}<span><strong>{item.name}</strong><small>@{handle}</small></span></button>;})}</div>;}
 function replyForm(target:string){return <form className="tw-reply-form" onSubmit={e=>{e.preventDefault();void act('reply',target,reply,false);}}><div className="tw-compose-input"><textarea autoFocus={replyTarget===target&&target!==thread} disabled={busy||state.ended} aria-label={translate('twitter.replyContent')} maxLength={280} placeholder={uiText("write_your_reply")} value={reply} onChange={e=>{setReply(e.target.value);setMentionIndex(0);setMentionDismissed(false);}} onKeyDown={e=>composeKeys(e,reply,setReply,()=>void act('reply',target,reply,false))}/>{mentionPicker(reply,setReply)}</div><footer><small className="tw-reply-policy">{translate('twitter.replyNoImage')}</small><small>{reply.length}/280</small><button className="tw-primary" aria-busy={busyAction==='reply'} disabled={busy||state.ended||!reply.trim()}>{busyAction==='reply'?<LoaderCircle className="spin" size={15}/>:<Send size={15}/>}{uiText("reply")}</button></footer></form>;}
 function focusPost(id:string){setFocusedPost(id);setTab('all');setThread(id);setReplyTarget(id);setReply('');setPeople(null);}
 function rootPost(post:TwitterPost){let root=post,guard=0;while(root.replyTo&&t!.posts[root.replyTo]&&guard++<100)root=t!.posts[root.replyTo];return root;}
 function descendants(parentId:string){const result:TwitterPost[]=[],seen=new Set([parentId]),queue=[parentId];while(queue.length){const parent=queue.shift()!;for(const post of posts)if(post.replyTo===parent&&!seen.has(post.id)){seen.add(post.id);result.push(post);queue.push(post.id);}}return result;}
 function activeCount(values:Record<string,boolean>){return Object.values(values).filter(Boolean).length;}
 function sortedReplies(parentId:string){return posts.filter(post=>post.replyTo===parentId).sort((a,b)=>replySort==='earliest'?a.created-b.created||a.id.localeCompare(b.id):replySort==='liked'?activeCount(b.likes)-activeCount(a.likes)||a.created-b.created:(activeCount(b.likes)+descendants(b.id).length*2)-(activeCount(a.likes)+descendants(a.id).length*2)||a.created-b.created);}
 function imageState(post:TwitterPost){if(twitterPostPending(post))return <TwitterUpload label={translate('twitter.uploading')}/>;if(!post.image&&post.imageStatus)return <div className="tw-image-failed"><small className="tw-context">{post.imageStatusLabel??post.imageStatus}</small>{!post.replyTo&&<button type="button" disabled={busy||state.ended||!images} onClick={()=>void act('retry-image',post.id)}>{busyAction==='retry-image'&&busyTarget===post.id?<LoaderCircle className="spin" size={15}/>:<RotateCcw size={15}/>} {translate('twitter.retryImage')}</button>}</div>;return null;}
 function twitterText(value:string):ReactNode{const lookup=new Map(Object.entries(t!.accounts).filter(([id])=>!t!.blocks?.[me]?.[id]&&!t!.blocks?.[id]?.[me]).map(([id,account])=>[account.handle.toLowerCase(),id])),parts:ReactNode[]=[];let last=0;for(const match of value.matchAll(/(?<![\p{L}\p{N}_])(?:@([A-Za-z0-9_]{1,15})|#([\p{L}\p{N}_]{1,50}))/gu)){const broadcast=match[1]?.toLowerCase()==='all',id=match[1]&&!broadcast?lookup.get(match[1].toLowerCase()):undefined;if(match[1]&&!broadcast&&!id)continue;parts.push(value.slice(last,match.index));if(match[2])parts.push(<button type="button" className="tw-hashtag" key={match.index} onClick={()=>{setSearchQuery('#'+match[2]);switchTab('all');}}>#{match[2]}</button>);else if(broadcast)parts.push(<span className="tw-mention" key={match.index}><button type="button">{match[0]}</button></span>);else{const officialAccount=official(id!);parts.push(<span className="tw-mention" key={match.index}><button type="button" onClick={()=>visit(id!)}>@{match[1]}</button><span className="tw-account-card">{officialAccount?<span className="avatar tw-official-avatar"><img src={officialAccount.avatar} alt=""/></span>:<CharacterAvatar character={character(id!)}/>}<span><strong>{name(id!)}</strong><small>@{t!.accounts[id!].handle}</small></span><span className="tw-card-bio">{bio(id!)}</span></span></span>);}last=match.index!+match[0].length;}parts.push(value.slice(last));return <span data-i18n-skip>{parts}</span>;}
 function quoteCard(id:string,interactive=true){const quoted=t!.posts[id];if(!quoted)return <div className="tw-quote-card tw-quote-unavailable"><small>{translate('twitter.unavailablePost')}</small></div>;return <section className="tw-quote-card" role={interactive?'button':undefined} tabIndex={interactive?0:undefined} onClick={interactive?()=>focusPost(id):undefined} onKeyDown={interactive?e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focusPost(id);}}:undefined}><header><strong>{name(quoted.author)}</strong><small>@{t!.accounts[quoted.author]?.handle??quoted.author}</small></header><p>{twitterText(quoted.text)}</p>{quoted.image&&<img className="tw-quote-photo" src={quoted.image} alt=""/>}</section>;}
 function replyBranch(x:TwitterPost,isTop:boolean){const likes=Object.keys(x.likes).filter(id=>x.likes[id]),children=isTop?descendants(x.id).sort((a,b)=>a.created-b.created||a.id.localeCompare(b.id)):[],replyCount=descendants(x.id).length,expanded=isTop?fullReplies.has(x.id):true;return <div className="tw-reply-branch" key={x.id}><article className="tw-reply"><header>{account(x.author)}<time>{x.date} · {dayPhaseNames(x.date)[x.phase]}</time></header><p>{twitterText(x.text)}</p>{x.image&&<a className="tw-photo-link" href={x.image} target="_blank" rel="noreferrer"><img className="tw-photo" src={x.image} alt={x.text}/></a>}{imageState(x)}<footer><button onClick={()=>focusPost(x.id)}>{uiText("view_this_reply")}</button><button disabled={busy||state.ended||twitterPostPending(x)} onClick={()=>beginReply(x.id)}><MessageCircle size={15}/>{uiText("reply")} {replyCount||''}</button><button aria-label={translate('twitter.likeReply')} aria-pressed={!!x.likes[me]} disabled={busy||state.ended||twitterPostPending(x)} onClick={()=>void act('like',x.id)}><Heart size={15} fill={x.likes[me]?'currentColor':'none'}/>{likes.length}</button>{x.author===me&&<button className="tw-delete" aria-label={translate('twitter.deleteAction')} disabled={busy||state.ended||twitterPostPending(x)} onClick={()=>setDeletePost(x.id)}><Trash2 size={15}/></button>}</footer>{typing(x.id)}{replyTarget===x.id&&replyForm(x.id)}</article>{isTop&&children.length>0&&<button type="button" className="tw-replies-toggle" aria-expanded={expanded} onClick={()=>{const next=new Set(fullReplies);if(expanded)next.delete(x.id);else next.add(x.id);setFullReplies(next);}}>{expanded?uiText("collapse_replies"):uiText("show_remaining_replies",replyCount)}</button>}{expanded&&children.flatMap(c=>replyBranch(c,false))}</div>;}
function replyList(parentId:string){const replies=sortedReplies(parentId);if(!replies.length)return null;return <>{replies.map(x=>replyBranch(x,true))}</>;}
 function card(p:TwitterPost){const likes=Object.keys(p.likes).filter(id=>p.likes[id]),reposts=Object.keys(p.reposts).filter(id=>p.reposts[id]),quotes=posts.filter(x=>x.quoteTo===p.id),repostAccounts=[...new Set([...reposts,...quotes.map(x=>x.author)])],comments=descendants(p.id),canShare=!t!.accounts[p.author]?.private&&(!p.replyTo||!t!.accounts[rootPost(p).author]?.private),watchKey=postNotificationTokens(p.id).join('|');return <SeenTwitterPost id={p.id} watchKey={watchKey} onSeen={()=>markPostSeen(p.id)} key={p.id}>
  {p.replyTo&&<small className="tw-context">{uiText("reply")} {name(rootPost(p).author)} {uiText("s_post")}</small>}
  <header>{account(p.author)}<time>{p.date} · {dayPhaseNames(p.date)[p.phase]}</time></header>
  <p>{twitterText(p.text)}</p>{p.image&&<a className="tw-photo-link" href={p.image} target="_blank" rel="noreferrer"><img className="tw-photo" src={p.image} alt={p.text}/></a>}{p.quoteTo&&quoteCard(p.quoteTo)}
  {imageState(p)}
  <footer><button aria-label={uiText("view_replies")} disabled={twitterPostPending(p)} onClick={()=>{const open=thread!==p.id;setThread(open?p.id:'');setReplyTarget(open||focusedPost===p.id?p.id:'');setReply('');}}><MessageCircle size={17}/>{comments.length}</button><button aria-label={uiText("repost")} aria-expanded={repostTarget===p.id} aria-pressed={!!p.reposts[me]} disabled={busy||state.ended||twitterPostPending(p)||!canShare} onClick={()=>setRepostTarget(repostTarget===p.id?'':p.id)}><Repeat2 size={17}/>{repostAccounts.length}</button><button aria-label={uiText("like")} aria-pressed={!!p.likes[me]} disabled={busy||state.ended||twitterPostPending(p)} onClick={()=>void act('like',p.id)}><Heart size={17} fill={p.likes[me]?'currentColor':'none'}/>{likes.length}</button>{p.author===me&&<button className="tw-delete" aria-label={translate('twitter.deleteAction')} disabled={busy||state.ended||twitterPostPending(p)} onClick={()=>setDeletePost(p.id)}><Trash2 size={17}/></button>}</footer>
  {repostTarget===p.id&&<div className="tw-repost-menu"><button type="button" onClick={()=>void act('repost',p.id)}>{busyAction==='repost'&&busyTarget===p.id?<LoaderCircle className="spin" size={17}/>:<Repeat2 size={17}/>} {p.reposts[me]?translate('twitter.undoRepost'):translate('twitter.repostNow')}</button><button type="button" onClick={()=>{setQuoteTarget(p.id);setQuoteText('');setRepostTarget('');}}><Quote size={17}/>{translate('twitter.quotePost')}</button></div>}
  <div className="tw-details"><button onClick={()=>setPeople({title:translate('twitter.likedAccounts'),ids:likes})}>{uiText("who_likes")}</button><button onClick={()=>setPeople({title:translate('twitter.repostAccounts'),ids:repostAccounts})}>{uiText("who_forwarded")}</button></div>{typing(p.id)}
  {!twitterPostPending(p)&&(thread===p.id||focusedPost===p.id)&&<section className="tw-thread"><header className="tw-thread-header"><h4>{translate('twitter.thread')} · {comments.length}</h4><div role="group" aria-label={translate('twitter.replySort')}><button aria-pressed={replySort==='relevant'} onClick={()=>setReplySort('relevant')}>{translate('twitter.sortRelevant')}</button><button aria-pressed={replySort==='earliest'} onClick={()=>setReplySort('earliest')}>{translate('twitter.sortEarliest')}</button><button aria-pressed={replySort==='liked'} onClick={()=>setReplySort('liked')}>{translate('twitter.sortLiked')}</button></div></header>{replyList(p.id)}{!comments.length&&<p className="tw-context">{uiText("no_one_has_left_a_message_yet")}</p>}{replyTarget===p.id&&replyForm(p.id)}</section>}
 </SeenTwitterPost>;}
 const notificationReadSet=new Set(notificationRead.split('|').filter(Boolean)),notificationTokens=twitterNotificationTokens(t,me),hasUnreadNotifications=notificationTokens.some(token=>!notificationReadSet.has(token));
 function markNotificationRead(token:string){if(notificationReadSet.has(token))return;const next=[...notificationReadSet,token].filter(value=>notificationTokens.includes(value)).sort().join('|');setNotificationRead(next);try{localStorage.setItem(notificationStorageKey,next);window.dispatchEvent(new Event('makeine-twitter-read'));}catch{}}
 function clearAllNotifications(){const next=[...new Set(notificationTokens)].sort().join('|');setNotificationRead(next);try{localStorage.setItem(notificationStorageKey,next);window.dispatchEvent(new Event('makeine-twitter-read'));}catch{}}
 function postNotificationTokens(postId:string){return notificationTokens.filter(token=>token===`friend:${postId}`||token===`mention:${postId}`||token===`reply:${postId}`||token===`quote:${postId}`||token.startsWith(`like:${postId}:`)||token.startsWith(`repost:${postId}:`)||token.startsWith('notice:')&&t!.notices[token.slice(7)]?.postId===postId).filter(token=>!notificationReadSet.has(token));}
 function markPostSeen(postId:string){const related=postNotificationTokens(postId);if(!related.length)return;setNotificationRead(current=>{const active=new Set(notificationTokens),nextSet=new Set(current.split('|').filter(token=>active.has(token)));for(const token of related)nextSet.add(token);const next=[...nextSet].sort().join('|');try{localStorage.setItem(notificationStorageKey,next);window.dispatchEvent(new Event('makeine-twitter-read'));}catch{}return next;});}
 function openNotification(token:string,postId?:string,accountId?:string){markNotificationRead(token);if(postId)focusPost(postId);else if(accountId)visit(accountId);}
 const normalizedSearch=searchQuery.trim().toLocaleLowerCase().replace(/^[@#]/,''),searchAccounts=normalizedSearch?Object.keys(t.accounts).filter(id=>name(id).toLocaleLowerCase().includes(normalizedSearch)||(t.accounts[id]?.handle??id).toLocaleLowerCase().includes(normalizedSearch)):[];
 const matchesSearch=(post:TwitterPost)=>!normalizedSearch||post.text.toLocaleLowerCase().includes(normalizedSearch)||name(post.author).toLocaleLowerCase().includes(normalizedSearch)||(t.accounts[post.author]?.handle??post.author).toLocaleLowerCase().includes(normalizedSearch)||twitterHashtags(post.text).some(tag=>tag.toLocaleLowerCase().includes(normalizedSearch));
 const visible=focusedPost?posts.filter(p=>p.id===focusedPost):posts.filter(p=>tab==='profile'?!p.replyTo&&(p.author===profile||p.reposts[profile]):tab==='home'?!p.replyTo&&(p.author===me||t.following[me]?.[p.author]||Object.keys(p.reposts).some(id=>p.reposts[id]&&t.following[me]?.[id])):matchesSearch(p));
 return <div className="tw-shell">{onClose&&<button type="button" className="tw-app-close" aria-label={translate('twitter.closeApp')} onClick={onClose}><X size={21}/></button>}<nav className="tw-nav" aria-label={uiText("twitter_tour")}><TwitterBird size={34}/>{[['home',uiText("home"),Home],['all',uiText("explore"),RefreshCw],['people',uiText("account_number"),Users],['notifications',uiText("notifications"),Bell]].map(([id,label,Icon])=>{const I=Icon as typeof Home;return <button className={id==='notifications'?'tw-notification-nav':''} key={String(id)} aria-label={String(label)} aria-current={!focusedPost&&tab===id?'page':undefined} onClick={()=>switchTab(String(id))}><I size={21}/><span>{String(label)}</span>{id==='notifications'&&hasUnreadNotifications&&<i className="tw-nav-notification-dot" aria-label={translate('twitter.unreadNotice')}/>}</button>;})}<button aria-label={uiText("profile")} onClick={()=>visit(me)}><CharacterAvatar character={character(me)}/><span>{uiText("profile")}</span></button></nav>
 <main className="tw-main" ref={mainRef}><header className="tw-title">{focusedPost&&<button className="tw-back" aria-label={t.posts[focusedPost]?.replyTo?translate('twitter.backToOriginal'):translate('twitter.backToList')} onClick={()=>{const current=t.posts[focusedPost];if(current?.replyTo)focusPost(rootPost(current).id);else{setFocusedPost('');setThread('');setReplyTarget('');}}}><ArrowLeft size={20}/></button>}<div><h2>{focusedPost?(t.posts[focusedPost]?.replyTo?translate('twitter.commentTitle'):translate('twitter.postTitle')):tab==='profile'?name(profile):({home:uiText("home"),all:uiText("explore_2"),people:uiText("people_you_know_2"),notifications:uiText("notifications")} as Record<string,string>)[tab]}</h2><small>{state.date} · {dayPhaseNames(state.date)[state.phase]}</small></div><TwitterBird size={22}/></header>
 {(error||notice)&&<div className="tw-toast-region" aria-live="polite"><p className={'tw-toast '+(error?'tw-error':'')} role={error?'alert':'status'}>{error||notice}</p></div>}
 {!focusedPost&&tab==='all'&&<section className="tw-search"><label><Search size={18}/><input value={searchQuery} onChange={event=>setSearchQuery(event.target.value)} placeholder={translate('twitter.searchPlaceholder')} aria-label={translate('twitter.searchLabel')}/></label>{trends.length>0&&<div className="tw-trend-chips">{trends.map(item=><button type="button" key={item.tag} onClick={()=>setSearchQuery('#'+item.tag)}>#{item.tag}<small>{item.posts} {translate('twitter.postUnit')}</small></button>)}</div>}{searchQuery&&searchAccounts.length>0&&<div className="tw-search-accounts">{searchAccounts.slice(0,6).map(id=>account(id))}</div>}</section>}
 {!focusedPost&&(tab==='home'||tab==='all')&&<form className="tw-composer" onSubmit={e=>{e.preventDefault();void act('post','',text,photo);}}><div><CharacterAvatar character={character(me)}/><div className="tw-compose-input"><textarea disabled={busy||state.ended} aria-label={uiText("new_post")} placeholder={uiText("what_happened_today")} maxLength={280} value={text} onChange={e=>{setText(e.target.value);setMentionIndex(0);setMentionDismissed(false);}} onKeyDown={e=>composeKeys(e,text,setText,()=>void act('post','',text,photo))}/>{mentionPicker(text,setText)}</div></div><footer><label className="tw-photo-toggle"><input type="checkbox" checked={photo} disabled={busy||state.ended||!images} onChange={e=>setPhoto(e.target.checked)}/><span>{uiText("with_pictures")} {images?'':uiText("sd_is_not_enabled_yet")}</span></label><small>{text.length}/280</small><button className="tw-primary" aria-busy={busyAction==='post'} disabled={busy||state.ended||!text.trim()}>{busyAction==='post'?<LoaderCircle className="spin" size={15}/>:<Send size={15}/>}{uiText("post")}</button></footer></form>}
 {tab==='profile'&&<section className="tw-profile"><div className="tw-cover" style={official(profile)?{background:`linear-gradient(120deg,${official(profile)!.color},#15202b)`}:undefined}>{cover(profile)&&<img src={cover(profile)} alt=""/>}</div>{account(profile)}<div className="tw-profile-body"><p data-i18n-skip>{bio(profile)}</p><div className="tw-profile-actions">{follow(profile)}{profile!==me&&!t.blocks?.[me]?.[profile]&&<button type="button" className="tw-block" disabled={busy||state.ended} onClick={()=>setBlockTarget(profile)}><Ban size={14}/>{translate('twitter.block')}</button>}</div>{t.blocks?.[profile]?.[me]&&<p className="tw-block-note">{translate('twitter.blockedYou').replace('{handle}',t.accounts[profile]?.handle??profile)}</p>}{t.blocks?.[me]?.[profile]&&<p className="tw-block-note">{translate('twitter.blockedByYou').replace('{handle}',t.accounts[profile]?.handle??profile)}</p>}{profile===me&&<label className="tw-privacy-switch"><span><strong>{uiText("private_account")}</strong><small>{translate('twitter.privateConsent')}</small></span><Switch checked={!!t.accounts[me]?.private} disabled={busy||state.ended} onCheckedChange={value=>void setPlayerPrivate(value)}/></label>}<p className="tw-context">{t.accounts[profile]?.verified?translate('twitter.verifiedPublic'):t.accounts[profile]?.private?uiText("private_account_tracking_requires_consent_to_read"):uiText("public_account")}{official(profile)?.sourceUrl&&<> · <a href={official(profile)!.sourceUrl} target="_blank" rel="noreferrer">{translate('twitter.officialSource')}</a></>}</p><div className="tw-details"><button onClick={()=>setPeople({title:uiText("following"),ids:Object.keys(t.following[profile]??{}).filter(id=>t.following[profile][id])})}>{Object.values(t.following[profile]??{}).filter(Boolean).length} {uiText("following")}</button><button onClick={()=>setPeople({title:translate('twitter.followersTitle'),ids:Object.keys(t.following).filter(id=>t.following[id]?.[profile])})}>{Object.values(t.following).filter(x=>x[profile]).length} {uiText("followers")}</button></div></div></section>}
 {tab==='people'&&<section className="tw-list"><h3>{translate('twitter.peopleKnown')}</h3>{known.map(ch=><div key={ch.id}>{account(ch.id)}{follow(ch.id)}</div>)}<h3 className="tw-list-heading">{translate('twitter.officialAccounts')}</h3>{officialAccounts.map(item=><div key={item.id}>{account(item.id)}{follow(item.id)}</div>)}</section>}
 {tab==='notifications'&&<section className="tw-list tw-notifications"><div className="tw-notification-tools"><button type="button" disabled={!hasUnreadNotifications} onClick={clearAllNotifications}><CheckCheck size={16}/>{translate('twitter.clearNotifications')}</button></div><h3>{uiText("follow_requests")}</h3>{Object.keys(t.requests[me]??{}).filter(id=>t.requests[me][id]).map(id=><div key={id}>{account(id)}<span><button disabled={busy} onClick={()=>void act('accept',id)}>{uiText("allow")}</button><button disabled={busy} onClick={()=>void act('decline',id)}>{uiText("decline")}</button></span></div>)}{!Object.values(t.requests[me]??{}).some(Boolean)&&<p>{uiText("no_pending_follow_requests")}</p>}<h3>{uiText("recent_activity")}</h3>{Object.entries(t.notices).filter(([id])=>id!=='scheduler'&&!notificationReadSet.has(`notice:${id}`)).sort((a,b)=>b[1].created-a[1].created).map(([id,n])=><button className="tw-notification" key={id} onClick={()=>openNotification(`notice:${id}`,n.postId,n.accountId)}>{n.text}</button>)}{posts.filter(p=>p.author!==me&&t.following[me]?.[p.author]&&!p.replyTo&&!notificationReadSet.has(`friend:${p.id}`)).map(p=><button className="tw-notification" key={'friend'+p.id} onClick={()=>openNotification(`friend:${p.id}`,p.id)}>{name(p.author)} {translate('twitter.friendPosted')}{ p.text.slice(0,45)}</button>)}{posts.filter(p=>p.author!==me&&new RegExp('@'+(t.accounts[me]?.handle??me)+'\\b','i').test(p.text)&&!notificationReadSet.has(`mention:${p.id}`)).map(p=><button className="tw-notification" key={'mention'+p.id} onClick={()=>openNotification(`mention:${p.id}`,p.id)}>{name(p.author)} {translate('twitter.mentionedNotice')}{ p.text.slice(0,45)}</button>)}{posts.filter(p=>p.author===me).flatMap(p=>[...Object.keys(p.likes).filter(id=>p.likes[id]&&!notificationReadSet.has(`like:${p.id}:${id}`)).map(id=><button className="tw-notification" key={p.id+'l'+id} onClick={()=>openNotification(`like:${p.id}:${id}`,p.id)}>{name(id)} {uiText("like_your_post")}{p.text.slice(0,45)}</button>),...posts.filter(x=>x.replyTo===p.id&&!notificationReadSet.has(`reply:${x.id}`)).map(x=><button className="tw-notification" key={x.id} onClick={()=>openNotification(`reply:${x.id}`,x.id)}>{name(x.author)} {uiText("reply_2")}{x.text}</button>),...posts.filter(x=>x.quoteTo===p.id&&!notificationReadSet.has(`quote:${x.id}`)).map(x=><button className="tw-notification" key={'quote'+x.id} onClick={()=>openNotification(`quote:${x.id}`,x.id)}>{name(x.author)} {translate('twitter.quoteNotification')}{x.text.slice(0,45)}</button>),...Object.keys(p.reposts).filter(id=>p.reposts[id]&&!notificationReadSet.has(`repost:${p.id}:${id}`)).map(id=><button className="tw-notification" key={p.id+'r'+id} onClick={()=>openNotification(`repost:${p.id}:${id}`,p.id)}>{name(id)} {uiText("retweet_your_post")}{p.text.slice(0,45)}</button>)])}{!hasUnreadNotifications&&<p>{translate('twitter.noNotifications')}</p>}</section>}
 {!['people','notifications'].includes(tab)&&(visible.length?visible.map(card):<div className="tw-empty"><TwitterBird size={44}/><h3>{tab==='profile'&&t.blocks?.[profile]?.[me]?translate('twitter.blockEmptyYou'):tab==='profile'&&t.blocks?.[me]?.[profile]?translate('twitter.blockEmptyByYou'):tab==='profile'&&t.accounts[profile]?.private&&!canReadTwitter(t,me,profile)?uiText("these_posts_are_protected"):uiText("the_story_unfolds_on_the_timeline_too")}</h3><p>{tab==='profile'&&(t.blocks?.[profile]?.[me]||t.blocks?.[me]?.[profile])?translate('twitter.blockEmptyDescription'):uiText("follow_people_you_know_or_send_out_your_first_tweet_in_each_period_the_characters_will")}</p></div>)}
 </main><aside className="tw-aside"><h3>{uiText("everyday_toyohashi")}</h3><p>{uiText("a_few_complaints_a_little_something")}<br/>{uiText("sometimes_i_just_want_to_watch_silently")}</p>{trends.length>0&&<section className="tw-aside-trends"><h4>{translate('twitter.trendsNow')}</h4>{trends.map(item=><button type="button" key={item.tag} onClick={()=>{setSearchQuery('#'+item.tag);switchTab('all');}}><strong>#{item.tag}</strong><small>{item.posts} {translate('twitter.postUnitSeparator')} {item.authors} {translate('twitter.accountUnit')}</small></button>)}</section>}<section className="tw-aside-people" aria-labelledby="tw-following-heading"><h4 id="tw-following-heading">{translate('twitter.followingSection')}</h4>{asideFollowing.length?asideFollowing.map(id=><div key={id}>{account(id,true)}</div>):<small className="tw-aside-empty">{translate('twitter.followingEmpty')}</small>}</section><section className="tw-aside-people" aria-labelledby="tw-suggestions-heading"><h4 id="tw-suggestions-heading">{translate('twitter.suggestionsSection')}</h4>{asideSuggestions.length?asideSuggestions.map(ch=><div key={ch.id}>{account(ch.id,true)}</div>):<small className="tw-aside-empty">{translate('twitter.suggestionsEmpty')}</small>}</section><small className="tw-disclaimer">{uiText("fictional_in_game_twitter")}<br/>{uiText("it_never_connects_or_posts_to_a_real_social_network")}</small></aside>{people&&<div className="tw-dialog-backdrop" onClick={()=>setPeople(null)}><section className="tw-people-dialog" role="dialog" aria-modal="true" aria-labelledby="tw-people-title" onClick={e=>e.stopPropagation()}><header><h3 id="tw-people-title">{people.title}</h3><button type="button" onClick={()=>setPeople(null)}>{uiText("close")}</button></header><div className="tw-dialog-list">{people.ids.length?people.ids.map(id=><div key={id}>{account(id)}{follow(id)}</div>):<p>{uiText("no_one_yet")}</p>}</div></section></div>}{deletePost&&<div className="tw-dialog-backdrop" onClick={()=>setDeletePost('')}><section className="tw-delete-dialog" role="alertdialog" aria-modal="true" aria-labelledby="tw-delete-title" aria-describedby="tw-delete-description" onClick={e=>e.stopPropagation()}><span className="tw-delete-icon"><Trash2 size={24}/></span><h3 id="tw-delete-title">{translate('twitter.deleteTitle')}</h3><p id="tw-delete-description">{translate('twitter.deleteDescription')}</p><blockquote data-i18n-skip>{t.posts[deletePost]?.text}</blockquote><div><button type="button" onClick={()=>setDeletePost('')}>{translate('common.cancel')}</button><button type="button" className="tw-delete-confirm" disabled={busy} onClick={()=>void act('delete',deletePost)}>{translate('twitter.deleteConfirm')}</button></div></section></div>}
 <Dialog open={!!unfollowTarget} onOpenChange={open=>{if(!open&&!busy)setUnfollowTarget('');}}><DialogContent className="tw-unfollow-dialog" showCloseButton={!busy}><span className="tw-unfollow-icon"><UserMinus size={23}/></span><DialogTitle>{translate('twitter.unfollowTitle').replace('{name}',name(unfollowTarget))}</DialogTitle><DialogDescription>{translate('twitter.unfollowDescription').replace('{handle}',t.accounts[unfollowTarget]?.handle??unfollowTarget)}</DialogDescription><div className="tw-unfollow-actions"><button type="button" disabled={busy} onClick={()=>setUnfollowTarget('')}>{translate('common.cancel')}</button><button type="button" className="tw-unfollow-confirm" disabled={busy} onClick={()=>{const target=unfollowTarget;setUnfollowTarget('');void act('unfollow',target);}}>{translate('twitter.unfollowConfirm')}</button></div></DialogContent></Dialog>
 <Dialog open={!!blockTarget} onOpenChange={open=>{if(!open&&!busy)setBlockTarget('');}}><DialogContent className="tw-unfollow-dialog" showCloseButton={!busy}><span className="tw-unfollow-icon"><Ban size={23}/></span><DialogTitle>{translate('twitter.blockTitle').replace('{name}',name(blockTarget))}</DialogTitle><DialogDescription>{translate('twitter.blockDescription')}</DialogDescription><div className="tw-unfollow-actions"><button type="button" disabled={busy} onClick={()=>setBlockTarget('')}>{translate('common.cancel')}</button><button type="button" className="tw-unfollow-confirm" disabled={busy} onClick={()=>{const target=blockTarget;setBlockTarget('');void act('block',target);}}>{translate('twitter.block')}</button></div></DialogContent></Dialog>
 <Dialog open={!!quoteTarget} onOpenChange={open=>{if(!open&&!busy){setQuoteTarget('');setQuoteText('');}}}><DialogContent className="tw-quote-dialog" showCloseButton={!busy}><DialogTitle>{translate('twitter.quotePost')}</DialogTitle><DialogDescription>{translate('twitter.quoteHelp')}</DialogDescription><div className="tw-compose-input"><textarea autoFocus disabled={busy||state.ended} aria-label={translate('twitter.quoteContent')} maxLength={280} placeholder={translate('twitter.quotePlaceholder')} value={quoteText} onChange={e=>setQuoteText(e.target.value)} onKeyDown={e=>{if(!e.nativeEvent.isComposing&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy&&quoteText.trim())void act('quote',quoteTarget,quoteText);}}}/></div>{quoteTarget&&quoteCard(quoteTarget,false)}<footer><small>{quoteText.length}/280</small><button type="button" className="tw-primary" aria-busy={busyAction==='quote'} disabled={busy||state.ended||!quoteText.trim()} onClick={()=>void act('quote',quoteTarget,quoteText)}>{busyAction==='quote'?<LoaderCircle className="spin" size={16}/>:<Quote size={16}/>}{translate('twitter.publish')}</button></footer></DialogContent></Dialog>
 </div>;
}
