import type { Content, Character, StoryEvent } from "./types";
import { upgradeRoster, repairPortraits, defaultCharacterPrompts } from './roster';
import { upgradeStories } from './story';
import {fillSceneBackgrounds} from './scene-assets';
const source = "https://makeine-anime.com/character/";
const cast = [
  [
    "kazuhiko",
    "温水和彦",
    "ぬくみず かずひこ",
    "#8494a6",
    "一年級・主角",
    "喜歡輕小說，習慣觀察旁人，嘴上冷靜但會幫助別人。",
    1,
    false,
    1,
  ],
  [
    "anna",
    "八奈見杏菜",
    "やなみ あんな",
    "#4a93ef",
    "一年級・文藝社",
    "開朗、愛吃，與袴田草介是青梅竹馬；草介正與姬宮華戀交往。失戀後仍努力保持笑容。",
    2,
    true,
    1,
  ],
  [
    "lemon",
    "焼塩檸檬",
    "やきしお れもん",
    "#eba13f",
    "一年級・田徑社",
    "直率而有活力，擅長短跑。喜歡青梅竹馬綾野光希，面對他與朝雲千早的關係逐漸整理心情。",
    3,
    true,
    1,
  ],
  [
    "komari",
    "小鞠知花",
    "こまり ちか",
    "#e57180",
    "一年級・文藝社",
    "怕生，說話偶爾結巴，用訊息比較能表達自己。喜歡閱讀與寫作，曾喜歡文藝社的玉木學長。",
    4,
    true,
    1,
  ],
  [
    "kaju",
    "温水佳樹",
    "ぬくみず かじゅ",
    "#b287d4",
    "國二・妹妹",
    "和彥的妹妹，能幹而關心哥哥的交友情況；隨著互動加深，逐漸意識到自己對哥哥的心意或許不只是家人之間的依賴。",
    5,
    true,
    -1,
  ],
  [
    "tamaki",
    "玉木慎太郎",
    "たまき しんたろう",
    "#7c9e88",
    "三年級・文藝社長",
    "創作網路小說，照顧後輩，與月之木古都為青梅竹馬。",
    6,
    false,
    3,
  ],
  [
    "koto",
    "月之木古都",
    "つきのき こと",
    "#aa7aa1",
    "三年級・文藝社副社長",
    "擅長照顧社員，喜歡BL小說，與玉木彼此在意。",
    7,
    false,
    3,
  ],
  [
    "sosuke",
    "袴田草介",
    "はかまだ そうすけ",
    "#8193b8",
    "一年級・同班同學",
    "杏菜的青梅竹馬，開朗受歡迎，與華戀交往。",
    8,
    false,
    1,
  ],
  [
    "karen",
    "姫宮華恋",
    "ひめみや かれん",
    "#dea499",
    "一年級・同班同學",
    "杏菜的好友，華麗開朗的轉學生，與草介交往。",
    9,
    false,
    1,
  ],
  [
    "mitsuki",
    "綾野光希",
    "あやの みつき",
    "#8b9ec3",
    "一年級・同學",
    "喜歡書籍，檸檬的青梅竹馬，與千早交往。",
    10,
    false,
    1,
  ],
  [
    "chihaya",
    "朝雲千早",
    "あさぐも ちはや",
    "#ad9d81",
    "一年級・同學",
    "成績優秀，與光希在同一補習班，對他的事情十分上心。",
    11,
    false,
    1,
  ],
  [
    "amanatsu",
    "甘夏古奈美",
    "あまなつ こなみ",
    "#caa16a",
    "班導師",
    "教社會科，健忘，有時忘了和彥是自己班上的學生。",
    12,
    false,
    0,
  ],
  [
    "konuki",
    "小抜小夜",
    "こぬき さよ",
    "#9f83a7",
    "保健室老師",
    "觀察學生間的人際關係，是甘夏老師的舊識。維持教師界線。",
    13,
    false,
    0,
  ],
  [
    "shikiya",
    "志喜屋夢子",
    "しきや ゆめこ",
    "#ab91dc",
    "二年級・學生會書記",
    "外表華麗，說話慢、情緒平淡，與人相處有獨特距離感。",
    14,
    true,
    2,
  ],
  [
    "asami",
    "権藤アサミ",
    "ごんどう あさみ",
    "#96a394",
    "國二・佳樹好友",
    "個子高，講三河方言，常從佳樹口中聽說和彥。",
    15,
    false,
    -1,
  ],
  [
    "hibari",
    "放虎原ひばり",
    "ほうこばる ひばり",
    "#7386b1",
    "二年級・學生會長",
    "高挑而有氣勢，偶爾有天然的一面，重視校務。",
    16,
    false,
    2,
  ],
  [
    "tiara",
    "馬剃天愛星",
    "ばそり てぃあら",
    "#bf88bb",
    "一年級・學生會副會長",
    "做事認真，介意自己的名字，說話嚴謹但也有柔軟的一面。",
    17,
    true,
    1,
  ],
] as const;
export const characters: Character[] = cast.map(
  ([id, name, reading, color, role, bio, image, romance, year]) => ({
    id,
    name,
    reading,
    color,
    role,
    bio,
    romance,
    year,
    source,
    sprites: {
      normal: `https://makeine-anime.com/assets/img/character/img_main${String(image).padStart(2, "0")}.png`,
    },
    prompt: defaultCharacterPrompts[id]??'i18n:character.default',
  }),
);
const events: StoryEvent[] = [
  {
    id: "anna-first",
    title: "一張還沒結清的帳單",
    character: "anna",
    place: "cafe",
    month: 0,
    minYear: 1,
    minAffection: 0,
    prerequisite: "",
    kind: "canon-inspired",
    reference: "小說第1卷／動畫第1話：家庭餐廳的失戀與餐費。台詞與選項為同人改寫。",
    text: "八奈見看著對面空下來的座位，把吸管紙套折成小小一團。「溫水同學……你剛才有看到多少？」桌上的帳單似乎比這句問題還難回答。",
    choices: [
      {
        text: "把水推過去，先聽她說完。",
        delta: 3,
        reply: "「你意外地……還算會看氣氛呢。」她握住杯子，終於沒有再望向門口。",
        flag: "anna-listened",
      },
      {
        text: "餐費先借妳，之後慢慢還就好。",
        delta: 2,
        reply: "「那、那我用午餐還你！先說好，不可以催喔。」",
        flag: "lunch-promise",
      },
      {
        text: "既然他已經走了，就別再等了。",
        delta: -2,
        reply: "「我知道啦……只是知道和做得到是兩回事吧。」",
      },
    ],
    cg: "",
    repeatable: false,
  },
  {
    id: "lemon-first",
    title: "跑道外的短暫休息",
    character: "lemon",
    place: "track",
    month: 0,
    minYear: 1,
    minAffection: 0,
    prerequisite: "",
    kind: "original",
    reference: "參考第1–2卷的田徑社與青梅竹馬關係；本事件為原創。",
    text: "檸檬跑完最後一圈，靠著圍欄調整呼吸。「溫水，你也來運動？還是來研究這邊飲水機的水？」她笑起來，目光卻短暫飄向校門。",
    choices: [
      {
        text: "遞上水，問她今天跑得怎麼樣。",
        delta: 3,
        reply: "「最後一圈還可以更快。不過……謝謝你有看見。」",
        flag: "lemon-training",
      },
      {
        text: "我可以陪妳走一段緩和一下。",
        delta: 2,
        reply: "「那就別走太慢喔！……今天慢一點也沒關係。」",
      },
      {
        text: "妳是不是又在等綾野？",
        delta: -2,
        reply: "「……今天只是練習啦。」她重新綁緊鞋帶。",
      },
    ],
    cg: "",
    repeatable: false,
  },
  {
    id: "komari-first",
    title: "書頁裡的留白",
    character: "komari",
    place: "club",
    month: 0,
    minYear: 1,
    minAffection: 0,
    prerequisite: "",
    kind: "original",
    reference: "參考第1卷文藝社設定；本事件為原創。",
    text: "小鞠抱著幾本書，站在夠不到的書架前。「不、不用幫忙……」她說完，最上面那一本又滑了下來。",
    choices: [
      {
        text: "接住書，問她應該放在哪一格。",
        delta: 3,
        reply: "「那、那邊……謝謝。」她把書背的標籤轉給你看。",
        flag: "komari-books",
      },
      {
        text: "先把書放桌上，一起整理吧。",
        delta: 2,
        reply: "「你、你不要把順序弄亂。」她往旁邊挪出一張椅子。",
      },
      {
        text: "直接全部塞回書架。",
        delta: -2,
        reply: "「分、分類全亂掉了……！」",
      },
    ],
    cg: "",
    repeatable: false,
  },
];
for (const c of characters.filter((c) => c.romance)) {
  const place =
    c.id === "lemon" ? "track" : c.id === "anna" ? "cafe" : c.id === "komari" ? "club" : c.id === "kaju" ? "home" : "council";
  events.push({
    id: `${c.id}-trust`,
    title: (
      {
        anna: "不只是午餐的約定",
        lemon: "不必一直往前跑",
        komari: "把這篇故事交給你",
        shikiya: "慢半拍的邀請",
        tiara: "名字以外的事情",
        kaju: "不只是家人的晚安",
      } as Record<string, string>
    )[c.id],
    character: c.id,
    place,
    month: 0,
    minYear: 1,
    minAffection: 20,
    prerequisite: "",
    kind: "original",
    reference: "同人原創信任事件；保留角色性格與既有人際關係。",
    text: `放學後，${c.name}沒有立刻離開。「今天……可以再陪我一下嗎？」熟悉的日常裡，這次的邀請多了一點慎重。`,
    choices: [
      {
        text: "先聽她想說什麼，認真留下來。",
        delta: 5,
        reply: "那段沒有急著填滿的沉默，慢慢變成能安心說話的時間。",
        flag: `${c.id}-trust`,
      },
      {
        text: "今天有事，約好下次再見。",
        delta: 1,
        reply: "你們確定了下次的時間。好好說明理由，也是一種誠意。",
      },
      {
        text: "把這件事當成玩笑帶過。",
        delta: -4,
        reply: "她笑了一下，沒有把原本想說的話接下去。",
      },
    ],
    cg: "",
    repeatable: false,
  });
  events.push({
    id: `${c.id}-route`,
    title: "想一起走的那條路",
    character: c.id,
    place,
    month: 0,
    minYear: 2,
    minAffection: 55,
    prerequisite: `${c.id}-trust`,
    kind: "original",
    reference: "同人 IF 路線分歧，非原作既定戀愛結果。",
    text: `又過了一段日子。你發現自己總會在人群中先找${c.name}的身影。今天，輪到你把心情說清楚。`,
    choices: [
      {
        text: "我想更認真地了解妳。",
        delta: 6,
        reply: "沒有戲劇性的承諾。你們只是約定，下次也要好好見面。",
        flag: `route:${c.id}`,
      },
      {
        text: "能一直當朋友，也很珍貴。",
        delta: 2,
        reply: "她點點頭。你們的故事，還有很多頁沒有寫。",
        flag: `friend:${c.id}`,
      },
    ],
    cg: "",
    repeatable: false,
  });
}
events.push({
  id: "festival",
  title: "文藝社的文化祭",
  character: "komari",
  place: "club",
  month: 10,
  minYear: 1,
  minAffection: 8,
  prerequisite: "",
  kind: "canon-inspired",
  reference: "小說第3卷／動畫第9–11話文藝社文化祭主題；日期與對話為同人編排。",
  text: "展示桌上堆滿文學作品的介紹稿。小鞠反覆確認清單，連窗外的夕陽都忘了看。「這、這些我一個人……」",
  choices: [
    {
      text: "請她分配工作，一起把最後一頁完成。",
      delta: 5,
      reply: "「那、那你負責這邊。」她終於把清單分了一半給你。",
      flag: "festival-help",
    },
    {
      text: "告訴她休息一下也不會失敗。",
      delta: 2,
      reply: "她看了一眼時鐘，慢慢放下筆。",
    },
    {
      text: "代替她做所有決定。",
      delta: -3,
      reply: "「我、我也想自己做到……」",
    },
  ],
  cg: "",
  repeatable: false,
});
export const defaultContent: Content = {
  characters,
  events,
  places: [
    {
      id: "classroom",
      name: "石蕗高中・教室",
      subtitle: "窗邊的座位，還留著午後的光。",
      background: "",
      weights: { anna: 4, sosuke: 2, karen: 2, amanatsu: 1 },
      school: true,
    },
    {
      id: "club",
      name: "文藝社社辦",
      subtitle: "翻頁聲之間，故事悄悄開始。",
      background: "",
      weights: { komari: 6, anna: 2, tamaki: 1, koto: 1 },
      school: true,
    },
    {
      id: "track",
      name: "學校操場",
      subtitle: "跑過終點後，還有人在等你。",
      background: "",
      weights: { lemon: 8, mitsuki: 1 },
      school: true,
    },
    {
      id: "cafe",
      name: "家庭餐廳",
      subtitle: "一杯飲料，和說不完的話。",
      background: "",
      weights: { anna: 7, lemon: 1, karen: 1 },
      school: false,
    },
    {
      id: "bookstore",
      name: "精文館書店",
      subtitle: "在書架的另一邊，偶然遇見。",
      background: "",
      weights: { komari: 5, mitsuki: 3, chihaya: 2, tiara: 2 },
      school: false,
    },
    {
      id: "station",
      name: "豐橋車站",
      subtitle: "電車到站之前，再聊一下吧。",
      background: "",
      weights: { anna: 2, lemon: 2, shikiya: 2, tiara: 2, hibari: 1, "kaju": 1, "komari": 1 },
      school: false,
    },
    {
      id: "park",
      name: "豐橋綜合動植物公園",
      subtitle: "週末的風，吹散了那些心事。",
      background: "",
      weights: { anna: 3, lemon: 3, komari: 3, chihaya: 1 },
      school: false,
    },
    {
      id: "council",
      name: "學生會室",
      subtitle: "文件整理完以後，還有一點時間。",
      background: "",
      weights: { shikiya: 4, tiara: 4, hibari: 2 },
      school: true,
    },
    {
      id: "home",
      name: "溫水家",
      subtitle: "今天的最後一則訊息，會來自誰？",
      background: "",
      weights: { kaju: 8, asami: 1 },
      school: false,
    },
  ],
  settings: {
    town: "豐橋",
    startDate: "2026-07-13",
    graduationDate: "2029-03-01",
    encounterRate: 0.85,
    memoryChars: 2400,
    recentTurns: 10,
    systemPrompt: 'i18n:game.system.default',
  },
  assets: [],
};
// Unique IF scenes extend the shared route mechanics without rewriting canon relationships.
const unique: Record<string, { trust: string; route: string }> = {
  anna: {
    trust:
      "八奈見把便當盒推過來，卻沒有立刻談起菜色。「最近提起草介的時候，我好像沒有以前那麼難受了。」她盯著筷子，又急忙補上一句：「但這不代表你可以搶我的炸雞喔。」",
    route:
      "家庭餐廳的飲料杯換了好幾輪。八奈見忽然問：「你每次跟我吃飯，都是因為不方便拒絕嗎？」你搖頭。今天想說的話，似乎終於不能再拿餐費當藉口。",
  },
  lemon: {
    trust:
      "練習提早結束，檸檬坐在跑道旁的長椅上。「以前我以為，只要跑得夠快，就能趕上很多事情。」她看著自己的鞋尖。「可是有些事，不能只靠跑步呢。」",
    route:
      "檸檬沒有像往常一樣衝到前面。她和你並肩走著，腳步第一次配合了你的速度。「溫水，你明年……還會來看我比賽嗎？」你想給的答案，比明年還要長。",
  },
  komari: {
    trust:
      "小鞠傳來一份沒有標題的文稿，接著又補了三則「不准笑」。「這、這次不是社刊的稿子……只是想先給你看。」你發現最後一頁，是兩個不擅長說話的人慢慢成為朋友的故事。",
    route:
      "社辦只剩下你們。小鞠把修訂好的手稿交給你，封面上寫著你的名字。「你、你每次都會看完……所以最後一段，我想聽你的意見。」那一段的主角，正準備向重要的人伸出手。",
  },
  shikiya: {
    trust:
      "志喜屋把資料夾一本本排好，然後伸手拉住快要滑下桌面的紙。「溫水……今天，沒有走掉呢。」她停了很久。「跟你待著……不太累。」這一次，你聽懂了她緩慢的表達。",
    route:
      "學生會室外，志喜屋提起自己的畢業。「之後……不在這裡了。還能見面嗎？」你沒有把問題當成隨口的閒聊。要讓彼此的聯絡不只是學生會工作，需要一個認真的回答。",
  },
  tiara: {
    trust:
      "天愛星把檢查表對折。「你是不是也覺得，我太容易把事情看得很嚴重？」這次她沒有拿名字開頭糾正你，而是等著答案。桌上的文件已經整理完，剩下的是一段不用寫進會議紀錄的話。",
    route:
      "書店門口，天愛星發現你沒有叫她副會長。「現在是放學之後。」你說。她把買好的書抱緊了一點。「那……今天的事，也不用當成公務吧？」你們都明白，這次邀請的理由與學生會無關。",
  },
  kaju: {
    trust:
      "晚餐後，佳樹坐在沙發上抱著靠墊，忽然開口：「哥哥大人……最近回家都比較晚呢。」她沒有追問原因，只是把靠墊抱得更緊。「佳樹不是在生氣喔。只是……有點不習慣家裡只有自己。」你注意到她的耳尖微微泛紅。",
    route:
      "你洗完澡回到客廳，佳樹還沒去睡。她把膝蓋縮進毯子裡，抬頭看著你。「哥哥大人，佳樹有一件事……一直不知道該不該說。」她深吸一口氣。「喜歡哥哥這件事，佳樹已經分不清是因為你是家人，還是因為……你是你了。」",
  },
};
for (const [id, scenes] of Object.entries(unique)) {
  events.find((e) => e.id === id + "-trust")!.text = scenes.trust;
  events.find((e) => e.id === id + "-route")!.text = scenes.route;
}
const extra: [
  string,
  string,
  string,
  string,
  number,
  number,
  number,
  string,
  string,
  string,
  string,
][] = [
  [
    "summer-manuscript",
    "暑假的社刊草稿",
    "komari",
    "bookstore",
    8,
    1,
    5,
    "參考文藝社創作活動的同人日常。",
    "小鞠在書店的文具區比較兩種筆記本。「寫、寫不出來的時候……你會怎麼辦？」她手上的書籤已經折出一道淡淡的痕跡。",
    "一起找一本能帶來靈感的書。",
    "你們沒有急著找答案，先從喜歡的段落開始聊起。",
  ],
  [
    "summer-running",
    "傍晚的起跑線",
    "lemon",
    "park",
    8,
    1,
    8,
    "參考第2卷檸檬整理青梅竹馬心情的主題；非原作場景重現。",
    "檸檬在樹蔭下停住。「今天不計時。只是想跑。」你想起她總是努力笑著的樣子，便收起了手機裡的碼表。",
    "尊重她的節奏，等她跑完。",
    "「不用問我跑幾秒嗎？」她喘著氣，笑得比剛才自然。",
  ],
  [
    "autumn-lunch",
    "沒有藉口的午餐",
    "anna",
    "cafe",
    11,
    1,
    10,
    "同人原創；延續第1卷午餐與餐費關係。",
    "八奈見翻了翻記帳紙。「那個，今天的便當跟之前欠你的錢沒關係。」她說完立刻打開盒子，好像蓋子打開就能讓話題結束。",
    "接受她的好意，認真說謝謝。",
    "「也、也不用說得那麼正式啦。趁熱吃！」",
  ],
  [
    "winter-books",
    "冬天的書籤",
    "komari",
    "bookstore",
    12,
    1,
    15,
    "同人原創冬季事件。",
    "冷風吹進店門，小鞠把圍巾拉高。她拿著一張書籤猶豫很久，最後放進你手裡。「社、社刊校稿……辛苦了。」",
    "把書籤夾進正在讀的那本書。",
    "她看見書籤露出的邊角，低頭藏起一點笑意。",
  ],
  [
    "new-year-station",
    "新年第一班電車",
    "anna",
    "station",
    1,
    1,
    15,
    "同人原創新年事件。",
    "車站廣播響起。八奈見拿著熱飲，鼻尖被冷風吹紅。「今年的願望？當然是吃遍所有期間限定……還有，嗯，希望大家都好好的。」",
    "告訴她，今年也一起創造新的回憶。",
    "「說好了喔。第一件事，陪我去看那邊的新年菜單！」",
  ],
  [
    "senior-farewell",
    "學長姐留下的社刊",
    "komari",
    "club",
    2,
    1,
    10,
    "同人原創；玉木與月之木在主角高一時為高三。",
    "桌上放著玉木學長留下的文稿，古都學姊的註記擠滿頁邊。小鞠沉默了一會儿。「下、下一本……也得好好做出來。」",
    "與她一起列出下一期社刊的計畫。",
    "你們把第一個截止日寫上日曆。離別之後，社辦也還會有新的故事。",
  ],
  [
    "spring-goal",
    "新的學年，新的秒數",
    "lemon",
    "track",
    4,
    2,
    20,
    "同人原創高二事件。",
    "操場旁的新生正看著檸檬練習。她跑過來，拿出新寫的目標表。「學姊要更可靠一點才行。溫水，這次也拜託你了！」",
    "答應來看比賽，也提醒她別受傷。",
    "「知道啦！有人記得叮嚀，感覺也不錯。」",
  ],
  [
    "exam-future",
    "想去的地方",
    "tiara",
    "bookstore",
    11,
    3,
    30,
    "同人原創升學事件。",
    "升學指南排滿一整面書架。天愛星拿了兩本，又放回一本。「選了不同的地方，也不代表現在的關係就一定會消失……對吧？」",
    "支持她想走的路，約好繼續聯絡。",
    "她把真正想看的那本書拿回手中。「那你也要說到做到。」",
  ],
  [
    "last-club",
    "畢業前的最後一篇",
    "komari",
    "club",
    2,
    3,
    35,
    "同人原創畢業前事件。",
    "最後一期社刊攤在桌上。小鞠的手指停在作者欄。「三、三年……原來可以寫這麼多。」你發現她已經可以看著你，把整句話說完。",
    "留下給未來的自己的一段話。",
    "你們在空白頁上寫下約定，沒有把故事停在「完」這個字上。",
  ],
  [
    "umbrella",
    "突如其來的雨",
    "anna",
    "station",
    0,
    1,
    5,
    "同人原創突發事件。",
    "出站時突然下起雨。八奈見摸了摸書包，然後用一種非常有說服力的表情看向你的傘。「溫水同學……車站到那邊的店，很近吧？」",
    "一起在屋簷下等雨變小。",
    "雨點打在招牌上。你們聊著沒有什麼重要的事，卻都不急著結束。",
  ],
];
for (const [
  id,
  title,
  character,
  place,
  month,
  minYear,
  minAffection,
  reference,
  text,
  yes,
  reply,
] of extra) {
  events.push({
    id,
    title,
    character,
    place,
    month,
    minYear,
    minAffection,
    prerequisite: "",
    kind: "original",
    reference,
    text,
    choices: [
      { text: yes, delta: 4, reply, flag: id + "-shared" },
      {
        text: "說明自己有事，約好下次再見。",
        delta: 0,
        reply: "你們互相道別，把還沒說完的話留給下一次。",
      },
      {
        text: "打斷對方，催促趕快結束。",
        delta: -3,
        reply: "話題停在半途。你後來才發現，當時應該再多聽一點。",
      },
    ],
    cg: "",
    repeatable: false,
  });
}
Object.assign(defaultContent, fillSceneBackgrounds(upgradeStories(repairPortraits(upgradeRoster(defaultContent)))));
