export type Character = {
  social?: {lineAffection:number;twitterHandle:string;twitterPrivate:boolean;twitterAffection:number;twitterActivity?:'low'|'medium'|'high';twitterFollowBack?:boolean;twitterBio?:string;twitterCover?:string};
  gender?: 'male' | 'female' | 'unspecified';
  id: string;
  name: string;
  reading: string;
  color: string;
  role: string;
  bio: string;
  prompt: string;
  sprites: Record<string, string>;
  romance: boolean;
  year: number;
  source: string;
  avatar?: string;
  avatarCrop?: ImageCrop;
  spriteCrop?: ImageCrop;
  imageNote?: string;
  roles?: {year:number;month:number;day?:number;role:string;note:string}[];
  timeline?: {
    school: 'tsuwabuki' | 'middle' | 'ayame' | 'staff' | 'outside';
    baseGrade: number;
    debutYear: number;
    debutMonth: number;
    note: string;
  };
};
export type ImageCrop = { x:number; y:number; width:number; height:number; imageWidth:number; imageHeight:number; outline?:number[] };
export type Place = {
  campus?: 'tsuwabuki' | 'middle';
  id: string;
  name: string;
  subtitle: string;
  background: string;
  weights: Record<string, number>;
  school: boolean;
};
export type Choice = {
  intent?: 'listen';
  text: string;
  delta: number;
  reply: string;
  flag?: string;
};
export type StoryEvent = {
  maxYear?: number;
  script?: StoryLine[];
  id: string;
  title: string;
  character: string;
  place: string;
  month: number;
  minYear: number;
  minAffection: number;
  prerequisite: string;
  requiredEvents?: string[];
  kind: "canon-inspired" | "original";
  reference: string;
  text: string;
  choices: Choice[];
  cg: string;
  repeatable: boolean;
};
export type Content = {
  storyPacks?: string[];
  defaultOverrides?: string[];
  publicAccounts?: import('./twitter-public').TwitterPublicAccount[];
  characters: Character[];
  places: Place[];
  events: StoryEvent[];
  settings: {
    town: string;
    startDate: string;
    graduationDate: string;
    encounterRate: number;
    systemPrompt: string;
    memoryChars: number;
    recentTurns: number;
  };
  assets: {
    id: string;
    title: string;
    url: string;
    source: string;
    note: string;
  }[];
};
export type MemoryFact = { kind:'promise'|'relationship'|'event'|'preference'; text:string; date:string; phase:number; channel:string; evidence:string };
export type SocialMemoryEvent = {
  platform:'twitter';
  owner:string;
  ownerName:string;
  actorId:string;
  actorName:string;
  eventType:'post'|'reply'|'quote'|'mention'|'like'|'repost'|'follow'|'follow_request'|'follow_accept'|'follow_decline'|'unfollow'|'block'|'unblock';
  postId?:string;
  postAuthor?:string;
  postAuthorName?:string;
  targetId?:string;
  targetName?:string;
  quotedPostId?:string;
  quotedPostAuthor?:string;
  quotedPostAuthorName?:string;
};
export type MemoryEntry = { role:'user'|'assistant'; content:string; date?:string; phase?:number; channel?:'line'|'talk'|'scene'|'twitter'; social?:SocialMemoryEvent };
export type Memory = {
  important?: MemoryFact[];
  archive?: MemoryEntry[];
  summary: string;
  facts: string[];
  recent: MemoryEntry[];
  turns: number;
};
export type Dialogue = {
  /** Character sprite selected by the face-to-face dialogue tool. */
  expression?: string;
  choiceMode?: 'contextual';
  /** First line of the latest character reply within script, after history trimming. */
  replyStart?: number;
  aiSource?: string;
  navigation?: 'map';
  narration?: string;
  thought?: string | null;
  script?: StoryLine[];
  speaker: string;
  text: string;
  eventId?: string;
  choices?: Choice[];
  kind?: string;
  cg?: string;
};
export type GameState = {
  socialApps?: {line:boolean;twitter:boolean};
  twitter?: import('./twitter').TwitterState;
  version: 1;
  revision: number;
  sceneRevision?: number;
  runId?: string;
  storyIllustration?: { scene: string; remaining: number; recent: {date:string;phase:number;place:string;caption:string}[] };
  pendingDateInvitation?: {character:string;place:string;text:string};
  pendingDate?: {character:string;place:string;accepted:boolean};
  date: string;
  phase: number;
  location: string;
  character: string;
  affection: Record<string, number>;
  met: string[];
  contacts: string[];
  memories: Record<string, Memory>;
  completed: string[];
  flags: string[];
  gallery: string[];
  log: { date: string; speaker: string; text: string }[];
  messages: Record<string, { id?:string; phase?:number; from: string; text: string; date: string; image?: string; imageCaption?: string; readByPlayerAt?:number; readByCharacterAt?:number; conversationClosed?:boolean; expectsReply?:boolean }[]>;
  dialogue: Dialogue;
  ended: boolean;
  ending: string;
  route: string;
  seenEndings: string[];
  seed: number;
};
export type StoryLine = {kind:'narration'|'speech'|'thought';speaker?:string;text:string;expression?:string};
