import {roleStages} from '../core/role-stages';
import {validateContent} from '../server/validation';
import {mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const base='http://localhost:9487';
const response=await fetch(base+'/api/editor');
if(!response.ok)throw Error('無法讀取本機 editor');
const {content,revision}=await response.json();
const backupDir=join(tmpdir(),'makein-role-backups');
await mkdir(backupDir,{recursive:true});
const backup=join(backupDir,`content-${Date.now()}.json`);
await writeFile(backup,JSON.stringify(content,null,2));
for(const ch of content.characters)if(roleStages[ch.id])ch.roles=structuredClone(roleStages[ch.id]);
validateContent(content);
const save=await fetch(base+'/api/editor',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({type:'content',content,revision})});
const result=await save.json();
if(!save.ok)throw Error(result.error);
console.log({saved:result.ok,sourceSaved:result.sourceSaved,backup,characters:content.characters.length});
